### PR TITLE
Use win percentage to detect close games

### PR DESCRIPTION
**Pull request by red-scott**
Yahoo already does the work to project win percentage including outstanding players. Use that to project a close matchup instead of just looking for raw point totals that are close, but ignore cases where one team has many more players left to play.

Consider a matchup "close" if a team has less than a 70% chance of winning.

### CODE REVIEW

**Comment by landonp1203** [comment]
Ah, did not even know this was in the API!

**Comment by landonp1203** [comment]
Would you be able to write a unit test for this to show that it works since I am on vacation and unable to test it as of now without writing my own?  You can put it inside the `MatchUpDataTransformerKtTest` class.  Pull down `master` since I updated it with a test fix that #39 references.

**Comment by red-scott** [comment]
I'll see if I can get to it tomorrow, got the tests working so that's progress

**Comment by red-scott** [comment]
Using win percentage works great, but after two weekends, a team having a 10% chance before Monday night is a much better heuristic for a "close" game.

**Comment by landonp1203** [comment]
Has this been updated?

**Comment by red-scott** [comment]
It has not, I will say win % is the way to go and it works great. I adjusted it to be a 90% "win" threshold. Only thing that's stopped me is I hacked my current bot so much it was harder to get you a clean change. I'll try to get to this later today, shouldn't take long

**Pull request merged**
